    server:
      port: ${GREETING_PORT:8080}
     
    spring:
      application:
        name: greeting-service
      cloud:
        config:
          discovery:
            enabled: true
            service-id: config-server


